<a href="https://colab.research.google.com/github/LFagundesN/PythonQuizzes/blob/main/Quiz5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# QUIZ 5
Leticia Fagundes Netto

In [8]:
import pandas as pd
# Importing the pandas library.

In [20]:
# Path for the dataframes in github
books_url = "https://raw.githubusercontent.com/LFagundesN/PythonQuizzes/46facefbfdcfad46677af8653ce647d013efa356/Books.csv"
employee_url = "https://raw.githubusercontent.com/LFagundesN/PythonQuizzes/46facefbfdcfad46677af8653ce647d013efa356/Employee.csv"

# reading and transforming the csv files into dataframes
books_df = pd.read_csv(books_url)
employee_df = pd.read_csv(employee_url)

# Importing the dataframes from github

In [21]:
books_df.head()
# Show the first few rows to check

                   Title               Author      Genre    Year       Status
0  To Kill a Mockingbird           Harper Lee    Fiction  1960.0    Available
1                   1984        George Orwell  Dystopian  1949.0  Checked Out
2       The Great Gatsby  F. Scott Fitzgerald    Fiction  1925.0    Available
3    Pride and Prejudice          Jane Austen    Romance  1813.0    Available
4             The Hobbit       J.R.R. Tolkien    Fantasy  1937.0  Checked Out

In [22]:
employee_df.head()
# Show the first few rows to check

     Name   Department   Salary   Hire_Date      Status
0   Helen        Sales  55452.0  2016-08-28      Active
1  George  Engineering  87466.0  2016-11-13      Active
2    Fred      Finance  78793.0  2015-01-26      Active
3    Dana           HR  80924.0  2022-12-29      Active
4     Eli           HR  74193.0  2016-05-12  Terminated

I can't join the dataframes without an index.

In [18]:
left_join_no_key = employee_df.join(books_df, how='left')

# Attempt a LEFT join using .join() with no common key or index

ValueError: columns overlap but no suffix specified: Index(['Status'], dtype='object')

In [30]:
inner_join_no_key = employee_df.join(books_df, how='inner')

 # Attempt an INNER join using .join() with no common key or index

ValueError: columns overlap but no suffix specified: Index(['Status'], dtype='object')

Q1: What happens when you join without a common column or index?
<br>
It tries to join by index, but if there’s no shared index and columns overlap, it gives an error.
<br>
Also:
<br>
employee_df contains employee information (e.g. Name, Department, etc.)
<br>
books_df contains book information (e.g. Title, Genre, etc.)
<br>
There’s no natural relationship between the two.
<br>
<br>
Q2: Why is this join not useful?
<br>
Because there's no key to connect the data, and pandas can’t figure out how to line up the rows. You need a proper index or column to join on.

In [25]:
# Add a shared key column called Book_Index (1, 2, 3, ...)
books_df['Book_Index'] = range(1, len(books_df) + 1)
employee_df['Book_Index'] = range(1, len(employee_df) + 1)

# Set 'Book_Index' as the index in both DataFrames
books_df.set_index('Book_Index', inplace=True)
employee_df.set_index('Book_Index', inplace=True)

In [34]:
books_df.head()
# Show the first few rows to check

,Title,Author,Genre,Year,Status
Book_Index,,,,,
1,To Kill a Mockingbird,Harper Lee,Fiction,1960.0,Available
2,1984,George Orwell,Dystopian,1949.0,Checked Out
3,The Great Gatsby,F. Scott Fitzgerald,Fiction,1925.0,Available
4,Pride and Prejudice,Jane Austen,Romance,1813.0,Available
5,The Hobbit,J.R.R. Tolkien,Fantasy,1937.0,Checked Out

In [32]:
employee_df.head()
# Show the first few rows to check

              Name   Department   Salary   Hire_Date      Status
Book_Index
1            Helen        Sales  55452.0  2016-08-28      Active
2           George  Engineering  87466.0  2016-11-13      Active
3             Fred      Finance  78793.0  2015-01-26      Active
4             Dana           HR  80924.0  2022-12-29      Active
5              Eli           HR  74193.0  2016-05-12  Terminated

Both DataFrames had a column named 'Status', but they meant different things:
<br>
<br> - In employee_df: Status means employment status (e.g. Active, Terminated)
<br> - In books_df: Status means book availability (e.g. Available, Checked Out)
<br>
<br> When we joined them, pandas renamed the duplicate columns to avoid confusion:
<br>
<br> - Status_emp = from employee_df
<br> - Status_book = from books_df
<br>
This avoids a conflict and keeps both versions.

In [36]:
# Perform left join (keep all employees)
#GPT HELPED ME WITH THAT
left_join = employee_df.join(books_df, how='left', lsuffix='_emp', rsuffix='_book')

In [37]:
# Perform inner join (only where both sides have matching index)
#GPT HELPED ME WITH THAT
inner_join = employee_df.join(books_df, how='inner', lsuffix='_emp', rsuffix='_book')

In [42]:
left_join.head()
# Show the first few rows to check

,Name,Department,Salary,Hire_Date,Status_emp,Title,Author,Genre,Year,Status_book
Book_Index,,,,,,,,,,
1,Helen,Sales,55452.0,2016-08-28,Active,To Kill a Mockingbird,Harper Lee,Fiction,1960.0,Available
2,George,Engineering,87466.0,2016-11-13,Active,1984,George Orwell,Dystopian,1949.0,Checked Out
3,Fred,Finance,78793.0,2015-01-26,Active,The Great Gatsby,F. Scott Fitzgerald,Fiction,1925.0,Available
4,Dana,HR,80924.0,2022-12-29,Active,Pride and Prejudice,Jane Austen,Romance,1813.0,Available
5,Eli,HR,74193.0,2016-05-12,Terminated,The Hobbit,J.R.R. Tolkien,Fantasy,1937.0,Checked Out

In [43]:
inner_join.head()
# Show the first few rows to check

,Name,Department,Salary,Hire_Date,Status_emp,Title,Author,Genre,Year,Status_book
Book_Index,,,,,,,,,,
1,Helen,Sales,55452.0,2016-08-28,Active,To Kill a Mockingbird,Harper Lee,Fiction,1960.0,Available
2,George,Engineering,87466.0,2016-11-13,Active,1984,George Orwell,Dystopian,1949.0,Checked Out
3,Fred,Finance,78793.0,2015-01-26,Active,The Great Gatsby,F. Scott Fitzgerald,Fiction,1925.0,Available
4,Dana,HR,80924.0,2022-12-29,Active,Pride and Prejudice,Jane Austen,Romance,1813.0,Available
5,Eli,HR,74193.0,2016-05-12,Terminated,The Hobbit,J.R.R. Tolkien,Fantasy,1937.0,Checked Out

In [48]:
# Print selected columns from left join
print(left_join[['Name', 'Department', 'Title', 'Genre', 'Status_book']].head())

              Name   Department                  Title      Genre  Status_book
Book_Index
1            Helen        Sales  To Kill a Mockingbird    Fiction    Available
2           George  Engineering                   1984  Dystopian  Checked Out
3             Fred      Finance       The Great Gatsby    Fiction    Available
4             Dana           HR    Pride and Prejudice    Romance    Available
5              Eli           HR             The Hobbit    Fantasy  Checked Out

In [49]:
# Print selected columns from inner join
print(inner_join[['Name', 'Department', 'Title', 'Genre', 'Status_book']].head())

              Name   Department                  Title      Genre  Status_book
Book_Index
1            Helen        Sales  To Kill a Mockingbird    Fiction    Available
2           George  Engineering                   1984  Dystopian  Checked Out
3             Fred      Finance       The Great Gatsby    Fiction    Available
4             Dana           HR    Pride and Prejudice    Romance    Available
5              Eli           HR             The Hobbit    Fantasy  Checked Out

Which employees do not have a matching book?
<br>
0 employees — all employees were matched to a book (via the simulated Book_Index).

In [44]:
# Filter rows where the Title column is missing (no book match)
employees_without_books = left_join[left_join['Title'].isnull()]

# Count how many
print(len(employees_without_books))

0

What is the difference in row count between the left join and the inner join?
<br>
0 rows — both joins returned the same number of rows, meaning all rows matched.

In [45]:
print(len(left_join) - len(inner_join))

0

How many employees were matched to Fiction books?
<br>
6 employees were matched to books with the genre Fiction.

In [46]:
fiction_matches = left_join[left_join['Genre'] == 'Fiction']
print(len(fiction_matches))

6

How many books matched are Checked Out?
<br>
12 matched rows had a book with the status Checked Out.

In [47]:
checked_out_books = left_join[left_join['Status_book'] == 'Checked Out']
print(len(checked_out_books))

12

What would happen if you accidentally joined on the wrong index?
<br>
I would get incorrect matches, false informations and have a unrealistic dataframe.

## References

OpenAI. (2024). *ChatGPT* (May 2024 version) [Large language model]. https://chat.openai.com/